services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "1009:1009"
    ports:
      - "9090:9090" # 외부 : 내부
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1009:1009"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=exporter:1111@(mysql_host:3306)/
    ports:
      - "9104:9104"
    restart: unless-stopped